//! Which `role` each HTML element may take, and which ARIA attributes a role
//! requires: the tables behind the role checks in `htm.rs`.
//!
//! **Extracted, not transcribed**, from epubcheck 5.4.0's HTML grammar
//! (`schema/30/mod/html5/*.rnc` with EPUB's `epub-xhtml-inc.rnc` and
//! `epub-xhtml-integration.rnc`), the same way the role vocabulary in
//! `schemas/xhtml.rng` was: for each element, every `attribute role { string
//! "…" }` its attribute patterns reach. Where the grammar defines an element
//! more than once (an `a` with and without `href`, an `img` with and without
//! `alt`, the list items of different lists) the sets are **united**, so no
//! variant is ever stricter here than in epubcheck. An element the grammar
//! lets take any role is `None`; an element absent from the table is not
//! checked at all. A role's required attributes are the non-optional
//! `aria-*` parts of its `aria.<role>` pattern, which hold on every element
//! (measured against 5.4.0 on `h1`, `span`, `div` and `input`).
//!
//! Re-extract when epubcheck's HTML grammar changes; do not edit by hand.

/// Every role token the grammar knows.
pub(crate) const ALL_ROLES: &[&str] = &[
    "alert",
    "alertdialog",
    "application",
    "article",
    "banner",
    "blockquote",
    "button",
    "caption",
    "cell",
    "checkbox",
    "code",
    "columnheader",
    "combobox",
    "complementary",
    "contentinfo",
    "definition",
    "deletion",
    "dialog",
    "doc-abstract",
    "doc-acknowledgments",
    "doc-afterword",
    "doc-appendix",
    "doc-backlink",
    "doc-biblioentry",
    "doc-bibliography",
    "doc-biblioref",
    "doc-chapter",
    "doc-colophon",
    "doc-conclusion",
    "doc-cover",
    "doc-credit",
    "doc-credits",
    "doc-dedication",
    "doc-endnote",
    "doc-endnotes",
    "doc-epigraph",
    "doc-epilogue",
    "doc-errata",
    "doc-example",
    "doc-footnote",
    "doc-foreword",
    "doc-glossary",
    "doc-glossref",
    "doc-index",
    "doc-introduction",
    "doc-noteref",
    "doc-notice",
    "doc-pagebreak",
    "doc-pagefooter",
    "doc-pageheader",
    "doc-pagelist",
    "doc-part",
    "doc-preface",
    "doc-prologue",
    "doc-pullquote",
    "doc-qna",
    "doc-subtitle",
    "doc-tip",
    "doc-toc",
    "document",
    "emphasis",
    "feed",
    "figure",
    "form",
    "graphics-document",
    "graphics-object",
    "graphics-symbol",
    "grid",
    "gridcell",
    "group",
    "heading",
    "image",
    "img",
    "insertion",
    "link",
    "list",
    "listbox",
    "listitem",
    "log",
    "main",
    "marquee",
    "math",
    "menu",
    "menubar",
    "menuitem",
    "menuitemcheckbox",
    "menuitemradio",
    "meter",
    "navigation",
    "none",
    "note",
    "option",
    "paragraph",
    "presentation",
    "progressbar",
    "radio",
    "radiogroup",
    "region",
    "row",
    "rowgroup",
    "rowheader",
    "scrollbar",
    "search",
    "searchbox",
    "separator",
    "slider",
    "spinbutton",
    "status",
    "strong",
    "subscript",
    "superscript",
    "switch",
    "tab",
    "table",
    "tablist",
    "tabpanel",
    "term",
    "textbox",
    "time",
    "timer",
    "toolbar",
    "tooltip",
    "tree",
    "treegrid",
    "treeitem",
];

/// Elements whose roles are restricted: `Some(list)`, empty meaning "none".
/// Elements that take any role are `None`.
pub(crate) const ELEMENT_ROLES: &[(&str, Option<&[&str]>)] = &[
    ("a", None),
    ("abbr", None),
    ("address", None),
    ("area", Some(&["button", "link"])),
    (
        "article",
        Some(&[
            "application",
            "article",
            "document",
            "feed",
            "main",
            "none",
            "presentation",
            "region",
        ]),
    ),
    (
        "aside",
        Some(&[
            "complementary",
            "doc-dedication",
            "doc-example",
            "doc-footnote",
            "doc-glossary",
            "doc-pullquote",
            "doc-tip",
            "feed",
            "none",
            "note",
            "presentation",
            "region",
            "search",
        ]),
    ),
    ("audio", Some(&["application"])),
    ("b", None),
    ("base", Some(&[])),
    ("bdi", None),
    ("bdo", None),
    ("blockquote", None),
    (
        "body",
        Some(&["application", "document", "none", "presentation"]),
    ),
    ("br", Some(&["none", "presentation"])),
    (
        "button",
        Some(&[
            "button",
            "checkbox",
            "combobox",
            "gridcell",
            "link",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "option",
            "radio",
            "separator",
            "slider",
            "switch",
            "tab",
            "treeitem",
        ]),
    ),
    ("canvas", None),
    ("caption", Some(&[])),
    ("cite", None),
    ("code", None),
    ("col", Some(&[])),
    ("colgroup", Some(&[])),
    ("data", None),
    ("datalist", Some(&[])),
    ("dd", Some(&["definition"])),
    ("del", None),
    ("details", Some(&["group"])),
    ("dfn", None),
    ("dialog", Some(&["alertdialog", "dialog"])),
    ("div", None),
    ("dl", Some(&["group", "list", "none", "presentation"])),
    (
        "dt",
        Some(&["doc-biblioentry", "doc-endnote", "listitem", "term"]),
    ),
    ("em", None),
    (
        "embed",
        Some(&["application", "document", "img", "none", "presentation"]),
    ),
    (
        "fieldset",
        Some(&["group", "none", "presentation", "radiogroup"]),
    ),
    ("figcaption", Some(&["group", "none", "presentation"])),
    ("figure", None),
    (
        "footer",
        Some(&[
            "contentinfo",
            "doc-footnote",
            "group",
            "none",
            "presentation",
        ]),
    ),
    ("form", Some(&["form", "none", "presentation", "search"])),
    (
        "h1",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    (
        "h2",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    (
        "h3",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    (
        "h4",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    (
        "h5",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    (
        "h6",
        Some(&["doc-subtitle", "heading", "none", "presentation", "tab"]),
    ),
    ("head", Some(&[])),
    (
        "header",
        Some(&["banner", "doc-footnote", "group", "none", "presentation"]),
    ),
    ("hgroup", None),
    (
        "hr",
        Some(&["doc-pagebreak", "none", "presentation", "separator"]),
    ),
    ("html", Some(&[])),
    ("i", None),
    (
        "iframe",
        Some(&["application", "document", "img", "none", "presentation"]),
    ),
    (
        "img",
        Some(&[
            "button",
            "checkbox",
            "doc-cover",
            "img",
            "link",
            "math",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "none",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "scrollbar",
            "separator",
            "slider",
            "switch",
            "tab",
            "treeitem",
        ]),
    ),
    (
        "input",
        Some(&[
            "button",
            "checkbox",
            "combobox",
            "gridcell",
            "link",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "option",
            "radio",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "switch",
            "tab",
            "textbox",
            "treeitem",
        ]),
    ),
    ("ins", None),
    ("kbd", None),
    ("label", None),
    ("legend", Some(&[])),
    ("li", None),
    ("link", Some(&["link", "menuitem", "none", "presentation"])),
    ("main", Some(&["main"])),
    ("map", Some(&[])),
    ("mark", None),
    (
        "menu",
        Some(&[
            "group",
            "list",
            "listbox",
            "menu",
            "menubar",
            "none",
            "presentation",
            "radiogroup",
            "tablist",
            "toolbar",
            "tree",
        ]),
    ),
    ("meta", Some(&["menuitem", "none", "presentation"])),
    ("meter", Some(&[])),
    (
        "nav",
        Some(&[
            "doc-index",
            "doc-pagelist",
            "doc-toc",
            "menu",
            "menubar",
            "navigation",
            "none",
            "presentation",
            "tablist",
        ]),
    ),
    ("noscript", Some(&[])),
    ("object", Some(&["application", "document", "img"])),
    (
        "ol",
        Some(&[
            "group",
            "list",
            "listbox",
            "menu",
            "menubar",
            "none",
            "presentation",
            "radiogroup",
            "tablist",
            "toolbar",
            "tree",
        ]),
    ),
    ("optgroup", Some(&["group"])),
    ("option", Some(&["option"])),
    ("output", None),
    ("p", None),
    ("picture", Some(&[])),
    ("pre", None),
    ("progress", Some(&["progressbar"])),
    ("q", None),
    ("rb", None),
    ("rp", None),
    ("rt", None),
    ("rtc", None),
    ("ruby", None),
    ("s", None),
    ("samp", None),
    ("script", Some(&[])),
    (
        "search",
        Some(&["form", "group", "none", "presentation", "region", "search"]),
    ),
    (
        "section",
        Some(&[
            "alert",
            "alertdialog",
            "application",
            "banner",
            "complementary",
            "contentinfo",
            "dialog",
            "doc-abstract",
            "doc-acknowledgments",
            "doc-afterword",
            "doc-appendix",
            "doc-bibliography",
            "doc-chapter",
            "doc-colophon",
            "doc-conclusion",
            "doc-credit",
            "doc-credits",
            "doc-dedication",
            "doc-endnotes",
            "doc-epigraph",
            "doc-epilogue",
            "doc-errata",
            "doc-example",
            "doc-foreword",
            "doc-glossary",
            "doc-index",
            "doc-introduction",
            "doc-notice",
            "doc-pagelist",
            "doc-part",
            "doc-preface",
            "doc-prologue",
            "doc-pullquote",
            "doc-qna",
            "doc-toc",
            "document",
            "feed",
            "group",
            "log",
            "main",
            "marquee",
            "navigation",
            "none",
            "note",
            "presentation",
            "region",
            "search",
            "status",
            "tabpanel",
        ]),
    ),
    ("select", Some(&["combobox", "listbox", "menu"])),
    ("selectedcontent", None),
    ("slot", None),
    ("small", None),
    ("source", Some(&[])),
    ("span", None),
    ("strong", None),
    ("style", Some(&[])),
    ("sub", None),
    ("summary", None),
    ("sup", None),
    ("table", None),
    ("tbody", None),
    ("td", None),
    ("template", Some(&[])),
    ("textarea", Some(&["textbox"])),
    ("tfoot", None),
    ("th", None),
    ("thead", None),
    ("time", None),
    ("title", Some(&[])),
    ("tr", None),
    ("track", Some(&[])),
    ("u", None),
    (
        "ul",
        Some(&[
            "group",
            "list",
            "listbox",
            "menu",
            "menubar",
            "none",
            "presentation",
            "radiogroup",
            "tablist",
            "toolbar",
            "tree",
        ]),
    ),
    ("var", None),
    ("video", Some(&["application"])),
    ("wbr", Some(&["none", "presentation"])),
];

/// Roles that require an ARIA attribute, whatever element carries them.
pub(crate) const REQUIRED_ATTRS: &[(&str, &str)] = &[
    ("checkbox", "aria-checked"),
    ("combobox", "aria-expanded"),
    ("heading", "aria-level"),
    ("menuitemcheckbox", "aria-checked"),
    ("menuitemradio", "aria-checked"),
    ("meter", "aria-valuenow"),
    ("radio", "aria-checked"),
    ("scrollbar", "aria-valuenow"),
    ("slider", "aria-valuenow"),
    ("switch", "aria-checked"),
];
